# server.properties — Modded Crafters (Bedrock Dedicated Server, Linux)
# Gerado pelo setup do repositório. Ajuste à vontade; update.sh preserva este arquivo.

server-name=Modded Crafters
gamemode=survival
force-gamemode=false
difficulty=hard
allow-cheats=false
max-players=5
online-mode=true
allow-list=false
server-port=19132
server-portv6=19133
enable-lan-visibility=true
view-distance=8
tick-distance=4
player-idle-timeout=30
max-threads=0
level-seed=
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=true
compression-threshold=1
compression-algorithm=zlib
server-authoritative-movement=server-auth
player-movement-score-threshold=20
player-movement-action-direction-threshold=0.85
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
correct-player-movement=false
server-authoritative-block-breaking=true
chat-restriction=None
disable-player-interaction=false
client-side-chunk-generation-enabled=true
block-network-ids-are-hashes=true
disable-custom-skins=false
server-build-radius-ratio=Disabled
allow-outbound-script-debugging=false
allow-inbound-script-debugging=false
script-debugger-port=19144
emit-server-telemetry=false
level-type=DEFAULT
level-name=Survival
